### PR TITLE
fix(css): reference complete woff file, do not reference split woff files

### LINKED ISSUE #110: In Internet Explorer 11 truncated ellipsis do not render - they appear as squares
On Windows 10 Pro version 1709, Internet Explorer 11 version 11.64.16299.0 Update version 11.0.48.

When using the Plex font "IBM Plex Sans", for a line which is truncated due the line being too long, and the CSS text-overflow is set to ellipsis, instead of "..." appearing at the end, three squares appear at the end of the text.

This has been tried on Plex version 5.1, 4.3 and 4.1. In 5.1 and 4.3 the squares show:

image

In Plex 4.1 the ellipsis show:

image

I have reproduced the issue using stand alone HTML and the Plex on unpkg.com. In our actual application the fonts and Sass are copied into our distribution using webpack, but because I can reproduce stand-alone it appears to be something in the font.

Here is a ZIP with the tests:
[tests.zip](https://github.com/IBM/type/files/1517959/tests.zip)

`test - 41.html` uses Plex 4.1 and works. `test - 43.html` and `test - 51.html` display the issue in Internet Explorer 11. 

This also does not work in Internet Explorer 11 in Windows 7 Service Pack 1. It does work in the latest Chrome, Firefox and Edge browsers.

Thanks!

### PR DESCRIPTION
**Pull request by seejamescode**
This would close #110.

We discovered that IE11 needs `.woff` file references without unicode ranges. This places a `.woff` reference for the whole typeface weight above the unicode range references using `.woff2`. I kept the split `.woff` files so this would not be a breaking change.

It was tested and shown to use the `woff2` splits on Chrome, but the `woff` complete on IE11.

### CODE REVIEW

File: scripts/tools/index.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ exports.formatFilename = formatFilename;
  * `createFontFace` is used to generate the actual `@font-face` declarations
  * that get written to the appropriate files.
  */
-const createFontFace = (filename, family, weight, unicode) => {
+const createFontFace = (filename, family, weight, unicode = {type: ''}) => {
```
Comment (joshblack) [inline scripts/tools/index.js]: Do we need the default `type: ''` here, or just the object? e.g. `unicode = {}`. Just curious!
